language: node_js
node_js: node
before_script:
- npm install
script: npm start
env:
  global:
  - GIT_COMMITTER_NAME=Yugo Yagita
  - GIT_COMMITTER_EMAIL=2000ygkn0713@gmail.com
  - GIT_AUTHOR_NAME=Yugo Yagita
  - GIT_AUTHOR_EMAIL=2000ygkn0713@gmail
after_success:
- git add docs -f
- git commit -m '[bot] Automatic generation of html'
- '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && echo "OK :)"'
- '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push -f --quiet "https://${GH_TOKEN}@github.com/lit-kansai-members/music.git" master:master 2> /dev/null'
