language: node_js
node_js: node

before_script:
  - npm install
script: npm start

env:
  global:
    - GIT_COMMITTER_NAME=Yugo Yagita
    - GIT_COMMITTER_EMAIL=2000ygkn0713@gmail.com
    - GIT_AUTHOR_NAME=Yugo Yagita
    - GIT_AUTHOR_EMAIL=2000ygkn0713@gmail
    - secure: "NXi+SH8KgOjeCCwJlLh+eQcD2IwpsMZGJ5uFrFM1EJxjfw0EzoGE/GP2qQWfWDE92sqliEZhi6SAD2vDV1v/queUwEyRuO12KxnrP/tZuy702ka1vn4hDw6UNrwZmBBUwCB/pJrZKBLmYCjHM7eh1S0YVvs2nAiikUEYSYfZupSs3eIAaGnZLpctobgiDuam9ox+y0zGIgM3ZQ/iaYG9VFQC+O/QbnaOgudU5c1mjYYLeOt1xFPaY349SLE9/KAK5WPC2vPJ1GzfJRshOXo6WgSfaVrm5vJG5BIBEfLLp4vqTjL8AFcTMBawOrHy6bPATeBvLNBUDf5ZrQh0VEIM4wXjfpi/gtrf/mIfSI4n9kwA7xfKZMhe9SGJmrEsjzOxf29QjYimmsQv0cm8HL7TRxYzXwwc3Je7/L/wuwbLIrMAxo881w9G3apmQDLfW5D2Bu+dRaAbJ3xVgEhznWKp4n1SvBPfjWDfkgnoDIP/OXAk2Gs1HGNX9pGhpNCCijUWrMP9aSJcRYssi5LOPV3TqYKHrwwPsOPFN5LkH+L/o7+LsdtYMMi+sf2OAKTpLtiWvt8BEGb0UGIKPQ7qOk4YJXMXgRTcXnAKTgwfq2ZV9HEyH39hRzmEG8KJb/L/Wy8WHWLEEUtz7/ZE6d19AHYADdxmArXkEXvl9J2e5L2YqLk="

after_success:
  - git add docs -f
  - git commit -m '[bot] Automatic generation of html'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/lit-kansai-members/music.git master 2> /dev/null'
