language: node_js
node_js: node
before_script:
- npm install
script: npm start
env:
  global:
  - GIT_COMMITTER_NAME=Yugo Yagita
  - GIT_COMMITTER_EMAIL=2000ygkn0713@gmail.com
  - GIT_AUTHOR_NAME=Yugo Yagita
  - GIT_AUTHOR_EMAIL=2000ygkn0713@gmail
  - secure: idCbAwP4d9dkblNYgJZT91qVfA3r72gIQjq3UHPg9XdBtUTQFkkM7kCef+4barWCqtw80P1f5tZwkc7Ikrb5VZ+EfO7XzSUDOtXyLjIsfMOuzyS7/EN9PffjCrpiOfq3mT5w4eJKASl6LZIQs0H1Pzre08VORPHvjEeZ5ogKpYypwFoPxJ6e+67tsrtFgI0SuQM8gVQ17oBzuAqheuaTFXwvRWratCtzpUMGHoyGpeOA/4QZIFtYTAHtpBqH3BegHcwTVKYEbUBCUjthOTnbluQCnLMcasec7nAW7jagWWtVIRh1KF7zoFoEdx16nG+3uQi/xTVu8Q9lQpVP6eOb6WGN8uxoeFnywnSPNEY42bMcwo1T/ryz9k3WcmgUg1kYJs2GZHnaao+N3utM5SILL5Sax2jBCAI8o6OMIURlvVUCDnKAMVqndcYn7LV59TwGsVFTJQxfuf0cvyZoXBhZctPSIISnkGviIyXmJRM7xL36x6ejx/M7dKOuggMl8duj1JTAWP7V5M3XhhXVziw6rok8q86gnvQ7v+zg15WwvA1Ej81i+BvzJqaGijYuvouZ3kRYSUIV5kA+aSJqKmb6ZiNAg6ISoELu5lai79vScPj4g9Gbu+8aRh98SdoueTELRO5XFWsC1Btq8siS3J2H+PmndFCVDxcHFZqDY+z3kZg=
after_success:
- git add docs -f
- git commit -m '[bot] Automatic generation of html'
- '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && echo "OK :)"'
- '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push -f --quiet "https://${GH_TOKEN}@github.com/lit-kansai-members/music.git"
  master:master 2> /dev/null'
