language: node_js
node_js: node
sudo: false
cache:
  yarn: true
  directories:
  - node_modules

env:
  global:
  - GIT_COMMITTER_NAME="Yugo Yagita"
  - GIT_COMMITTER_EMAIL=2000ygkn0713@gmail.com
  - GIT_AUTHOR_NAME="Yugo Yagita"
  - GIT_AUTHOR_EMAIL=2000ygkn0713@gmail

before_script:
- yarn
- git clone -b gh-pages https://github.com/lit-kansai-members/music.git pages

script: npm start

after_success:
- |

    $(npm bin)/set-up-ssh --key "$encrypted_c4ab829a9399_key" \
                          --iv "$encrypted_c4ab829a9399_iv" \
                          --path-encrypted-key ".travis/github_deploy_key.enc"
-|

    # Add the SSH-related commands here, see:
    # https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md#26-set-up-ssh-connection-for-travis-ci

    $(npm bin)/update-branch --commands "npm run build" \
                             --commit-message "Hey GitHub, this content is for you! [skip ci]" \
                             --directory "dist" \
                             --distribution-branch "gh-pages" \
                             --source-branch "master"
