language: node_js
node_js: node
sudo: false
cache:
  yarn: true
  directories:
  - node_modules

env:
  global:
  - GH_USER_EMAIL="2000ygkn0713@gmail"
  - GH_USER_NAME="Yugo Yagita"

after_success:
- |

    $(npm bin)/set-up-ssh --key "$encrypted_c4ab829a9399_key" \
                          --iv "$encrypted_c4ab829a9399_iv" \
                          --path-encrypted-key ".travis/github_deploy_key.enc"
- |

    # Add the SSH-related commands here, see:
    # https://github.com/alrra/travis-scripts/blob/master/doc/github-deploy-keys.md#26-set-up-ssh-connection-for-travis-ci

    $(npm bin)/update-branch --commands "npm run build" \
                             --commit-message "[build] build page. [skip ci]" \
                             --directory "build" \
                             --distribution-branch "gh-pages" \
                             --source-branch "master"
